-- Create recruit_items table for jobs, contests, and events
CREATE TABLE IF NOT EXISTS "public"."recruit_items" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "title" text NOT NULL,
  "description" text NOT NULL,
  "type" text NOT NULL CHECK (type IN ('job', 'contest', 'event')),
  "date" date NOT NULL,
  "location" text,
  "prize" text,
  "salary" text,
  "company" text,
  "employment_type" text,
  "link" text,
  "thumbnail" text,
  "is_active" boolean DEFAULT true NOT NULL,
  "is_crawled" boolean DEFAULT false NOT NULL,
  "source_url" text,
  "crawled_at" timestamp with time zone,
  PRIMARY KEY ("id")
);

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_recruit_items_type ON "public"."recruit_items"(type);
CREATE INDEX IF NOT EXISTS idx_recruit_items_date ON "public"."recruit_items"(date);
CREATE INDEX IF NOT EXISTS idx_recruit_items_is_active ON "public"."recruit_items"(is_active);

-- Enable RLS
ALTER TABLE "public"."recruit_items" ENABLE ROW LEVEL SECURITY;

-- Policies

-- 1. Anyone can view active items
DROP POLICY IF EXISTS "Active recruit items are viewable by everyone." ON "public"."recruit_items";
CREATE POLICY "Active recruit items are viewable by everyone." ON "public"."recruit_items"
  FOR SELECT USING (is_active = true);

-- 2. Admins can do everything
DROP POLICY IF EXISTS "Admins can do everything on recruit items." ON "public"."recruit_items";
CREATE POLICY "Admins can do everything on recruit items." ON "public"."recruit_items"
  FOR ALL USING (
  auth.uid() IN (SELECT id FROM users WHERE role = 'admin')
);

-- Grant permissions
GRANT SELECT ON TABLE "public"."recruit_items" TO "anon";
GRANT SELECT ON TABLE "public"."recruit_items" TO "authenticated";
GRANT ALL ON TABLE "public"."recruit_items" TO "service_role";

-- Create crawl_logs table to track crawling history
CREATE TABLE IF NOT EXISTS "public"."crawl_logs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "type" text NOT NULL CHECK (type IN ('job', 'contest', 'event', 'all')),
  "status" text NOT NULL CHECK (status IN ('success', 'failed', 'partial')),
  "items_found" integer DEFAULT 0,
  "items_added" integer DEFAULT 0,
  "items_updated" integer DEFAULT 0,
  "error_message" text,
  "duration_ms" integer,
  PRIMARY KEY ("id")
);

-- Enable RLS for crawl_logs
ALTER TABLE "public"."crawl_logs" ENABLE ROW LEVEL SECURITY;

-- Only admins can view crawl logs
DROP POLICY IF EXISTS "Admins can view crawl logs." ON "public"."crawl_logs";
CREATE POLICY "Admins can view crawl logs." ON "public"."crawl_logs"
  FOR SELECT USING (
  auth.uid() IN (SELECT id FROM users WHERE role = 'admin')
);

-- Grant permissions for crawl_logs
GRANT SELECT ON TABLE "public"."crawl_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."crawl_logs" TO "service_role";
