-- Create banners table
CREATE TABLE IF NOT EXISTS "public"."banners" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "title" text NOT NULL,
  "description" text,
  "image_url" text NOT NULL,
  "link_url" text,
  "order" integer DEFAULT 0 NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "bg_color" text DEFAULT '#000000'::text,
  "text_color" text DEFAULT '#ffffff'::text,
  "position" text DEFAULT 'left'::text,
  PRIMARY KEY ("id")
);

-- Enable RLS
ALTER TABLE "public"."banners" ENABLE ROW LEVEL SECURITY;

-- Policies

-- 1. Anyone can view active banners
DROP POLICY IF EXISTS "Active banners are viewable by everyone." ON "public"."banners";
CREATE POLICY "Active banners are viewable by everyone." ON "public"."banners"
  FOR SELECT USING (is_active = true);

-- 2. Admins can do everything
DROP POLICY IF EXISTS "Admins can do everything on banners." ON "public"."banners";
CREATE POLICY "Admins can do everything on banners." ON "public"."banners"
  FOR ALL USING (
  auth.uid() IN (SELECT id FROM users WHERE role = 'admin')
);

-- Grant permissions (if needed for anon access)
GRANT SELECT ON TABLE "public"."banners" TO "anon";
GRANT SELECT ON TABLE "public"."banners" TO "authenticated";
GRANT ALL ON TABLE "public"."banners" TO "service_role";
