"use client";

import React, { useState, useRef } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Loader2, Wand2, Rocket, Share2, Download, ArrowRight, Check } from "lucide-react";
import { toast, Toaster } from "sonner";
import html2canvas from "html2canvas";

// --- Types & Data ---

interface LeanCanvasData {
  problem: string;
  customerSegments: string;
  uniqueValueProposition: string;
  solution: string;
  channels: string;
  revenueStreams: string;
  costStructure: string;
  keyMetrics: string;
  unfairAdvantage: string;
}

const initialData: LeanCanvasData = {
  problem: "",
  customerSegments: "",
  uniqueValueProposition: "",
  solution: "",
  channels: "",
  revenueStreams: "",
  costStructure: "",
  keyMetrics: "",
  unfairAdvantage: "",
};

// --- Page Component ---

export default function LeanCanvasPage() {
  const router = useRouter();
  const [topic, setTopic] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerated, setIsGenerated] = useState(false);
  const [canvasData, setCanvasData] = useState<LeanCanvasData>(initialData);
  const canvasRef = useRef<HTMLDivElement>(null);

  const handleGenerate = async () => {
    if (!topic.trim()) {
      toast.error("아이디어를 입력해주세요!");
      return;
    }

    setIsLoading(true);
    
    try {
        const response = await fetch('/api/ai/generate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ type: 'lean-canvas', topic })
        });

        if (!response.ok) {
            const errData = await response.json();
            throw new Error(errData.error || 'AI 생성 실패');
        }

        const data = await response.json();
        setCanvasData(data);
        setIsGenerated(true);
        toast.success("린 캔버스가 생성되었습니다!");
    } catch (error) {
        console.error(error);
        toast.error("생성에 실패했습니다. 잠시 후 다시 시도해주세요.");
    } finally {
        setIsLoading(false);
    }
  };

  const handleChange = (key: keyof LeanCanvasData, value: string) => {
    setCanvasData((prev) => ({ ...prev, [key]: value }));
  };

  const handleDownloadImage = async () => {
    if (!canvasRef.current) return;
    try {
      const canvas = await html2canvas(canvasRef.current, { scale: 2 });
      const link = document.createElement("a");
      link.download = `${topic || "leancanvas"}-vibefolio.png`;
      link.href = canvas.toDataURL();
      link.click();
      toast.success("이미지로 저장되었습니다.");
    } catch (e) {
      console.error(e);
      toast.error("저장에 실패했습니다.");
    }
  };

  const handleStartProject = () => {
    // Format to Markdown
    const content = `
## 🚀 ${topic ? topic + ' - ' : ''}린 캔버스 기획안

> **Generated by Vibefolio AI Planner**

### 1. 문제 (Problem)
${canvasData.problem}

### 2. 고객군 (Customer Segments)
${canvasData.customerSegments}

### 3. 고유 가치 제안 (Unique Value Proposition)
${canvasData.uniqueValueProposition}

### 4. 솔루션 (Solution)
${canvasData.solution}

### 5. 경쟁 우위 (Unfair Advantage)
${canvasData.unfairAdvantage}

### 6. 채널 (Channels)
${canvasData.channels}

### 7. 핵심 지표 (Key Metrics)
${canvasData.keyMetrics}

### 8. 비용 구조 (Cost Structure)
${canvasData.costStructure}

### 9. 수익원 (Revenue Streams)
${canvasData.revenueStreams}
    `.trim();

    // Save to LocalStorage for import
    localStorage.setItem('project_import_content', content);
    localStorage.setItem('project_import_title', topic);
    localStorage.setItem('project_import_type', 'lean_canvas');
    
    // Redirect
    toast.success("프로젝트 에디터로 이동합니다...");
    setTimeout(() => {
        router.push('/project/upload');
    }, 1000);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <Toaster position="top-center" richColors />
      
      {/* Hero Section */}
      <div className="bg-[#0a0a0a] text-white pt-24 pb-32 px-4 relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-full opacity-[0.15] bg-[url('https://grainy-gradients.vercel.app/noise.svg')]"></div>
        <div className="absolute -top-[20%] right-[10%] w-[500px] h-[500px] bg-purple-900/40 rounded-full blur-[120px]"></div>
        <div className="absolute bottom-[10%] left-[10%] w-[400px] h-[400px] bg-green-900/30 rounded-full blur-[100px]"></div>

        <div className="max-w-4xl mx-auto text-center relative z-10 animate-in fade-in slide-in-from-bottom-6 duration-700">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-white/5 rounded-full text-xs font-bold text-green-400 mb-6 border border-white/10 backdrop-blur-sm">
            <Wand2 className="w-3 h-3" />
            Vibefolio AI Labs
          </div>
          <h1 className="text-4xl md:text-6xl font-black mb-6 leading-tight tracking-tight">
            아이디어를 <span className="text-transparent bg-clip-text bg-gradient-to-r from-green-400 to-emerald-400">비즈니스로</span>
          </h1>
          <p className="text-lg text-gray-400 mb-10 max-w-2xl mx-auto leading-relaxed">
            한 줄의 아이디어만 입력하세요. <br className="hidden md:block"/>
            AI가 <b>린 캔버스(Lean Canvas)</b>를 완벽하게 작성해드립니다.
          </p>

          <div className="max-w-xl mx-auto relative group">
            <div className="absolute -inset-1 bg-gradient-to-r from-green-500 to-purple-600 rounded-2xl blur opacity-30 group-hover:opacity-50 transition-opacity"></div>
            <div className="relative bg-white rounded-xl p-2 flex items-center shadow-2xl">
              <Input
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
                placeholder="어떤 서비스를 만들고 싶으신가요?"
                className="border-0 h-12 text-lg text-black placeholder:text-gray-400 focus-visible:ring-0 bg-transparent px-4 font-medium"
              />
              <Button 
                onClick={handleGenerate} 
                disabled={isLoading}
                className="h-12 px-6 bg-black hover:bg-gray-800 text-white rounded-lg font-bold text-base gap-2 transition-all min-w-[120px]"
              >
                {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Wand2 className="w-5 h-5" />}
                {isLoading ? "작성 중" : "생성하기"}
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Canvas Section */}
      <div className="-mt-20 container mx-auto px-4 pb-20 relative z-20">
        
        {/* Tool Switcher Tabs */}
        <div className="flex justify-center mb-8">
            <div className="bg-white/10 backdrop-blur-md p-1 rounded-xl flex gap-1 border border-white/20">
                <button className="px-6 py-2.5 bg-white text-black rounded-lg font-bold text-sm shadow-lg transition-all flex items-center gap-2">
                    <span className="text-lg">📊</span> 린 캔버스
                </button>
                <button 
                    onClick={() => router.push('/tools/persona')}
                    className="px-6 py-2.5 text-white/70 hover:text-white hover:bg-white/10 rounded-lg font-medium text-sm transition-all flex items-center gap-2"
                >
                    <span className="text-lg opacity-70">👤</span> 페르소나 정의 <span className="text-[10px] bg-green-500 text-black px-1.5 py-0.5 rounded-full font-bold">New</span>
                </button>
            </div>
        </div>

        <div className={`transition-all duration-1000 ${isGenerated ? 'opacity-100 translate-y-0' : 'opacity-100 translate-y-0'}`}>
            
            {/* Toolbar */}
            <div className="flex justify-between items-center mb-6 pl-2 pr-2">
                <h2 className="text-xl font-bold flex items-center gap-2 text-white/90">
                    <span className="bg-white/10 p-1.5 rounded-md"><Rocket className="w-4 h-4 text-green-400" /></span>
                    린 캔버스 미리보기
                </h2>
                <div className="flex gap-3">
                    <Button variant="secondary" onClick={handleDownloadImage} disabled={!isGenerated} className="gap-2 bg-white hover:bg-gray-100 text-black border border-transparent shadow-lg text-sm font-semibold">
                        <Download className="w-4 h-4" /> 이미지 저장
                    </Button>
                    <Button onClick={handleStartProject} disabled={!isGenerated} className="bg-green-600 hover:bg-green-700 text-white gap-2 font-bold shadow-lg shadow-green-900/20 hover:translate-y-[-2px] transition-all">
                        프로젝트 시작하기 <ArrowRight className="w-4 h-4" />
                    </Button>
                </div>
            </div>

            {/* Canvas Container -> Paper Style */}
            <div 
               ref={canvasRef} 
               className="bg-white rounded-sm shadow-2xl overflow-hidden"
               style={{ minHeight: '800px' }} // A4 비율 비슷하게
            >
                {/* Canvas Header */}
                <div className="p-8 border-b-2 border-black flex justify-between items-end bg-gray-50/50">
                    <div>
                        <h3 className="text-3xl font-black text-gray-900 tracking-tight">{topic || "Lean Canvas Title"}</h3>
                        <p className="text-sm text-gray-500 mt-2 font-medium">Business Model & Strategy</p>
                    </div>
                     <div className="text-right flex flex-col gap-1">
                        <div className="text-xs text-gray-400 font-bold uppercase tracking-widest">Designed By</div>
                        <div className="font-bold text-gray-900">Vibefolio AI</div>
                        <div className="text-xs text-gray-400 font-mono mt-1">{new Date().toLocaleDateString()}</div>
                    </div>
                </div>

                {/* THE GRID: 10 Columns */}
                <div className="grid grid-cols-1 md:grid-cols-10 border-black border-l-0 border-r-0 border-b-0 min-h-[700px]">
                    
                    {/* 1. Problem (Col 1-2 / Row 1-2) */}
                    {/* Desktop: col-span-2, row-span-2 */}
                    <div className="md:col-span-2 md:row-span-2 border-r border-b border-black/10 md:border-black p-0 flex flex-col h-full bg-white">
                        <CanvasHeader number="1" title="Problem" subtitle="고객의 문제" icon="🔥" />
                        <CanvasBody value={canvasData.problem} onChange={(v) => handleChange("problem", v)} />
                    </div>

                    {/* 4. Solution (Col 3-4 / Row 1) */}
                    <div className="md:col-span-2 md:row-span-1 border-r border-b border-black/10 md:border-black p-0 flex flex-col h-full bg-white">
                         <CanvasHeader number="4" title="Solution" subtitle="해결책" icon="💡" />
                         <CanvasBody value={canvasData.solution} onChange={(v) => handleChange("solution", v)} />
                    </div>

                    {/* 3. UVP (Col 5-6 / Row 1-2) -> Center */}
                    <div className="md:col-span-2 md:row-span-2 border-r border-b border-black/10 md:border-black p-0 flex flex-col h-full bg-slate-50 relative">
                         {/* Centered UVP Highlight */}
                         <CanvasHeader number="3" title="Value Proposition" subtitle="차별화된 가치" icon="💎" className="text-purple-700" />
                         <CanvasBody value={canvasData.uniqueValueProposition} onChange={(v) => handleChange("uniqueValueProposition", v)} className="text-center font-medium text-gray-800" />
                         <div className="absolute top-0 right-0 p-2 opacity-10 pointer-events-none">
                            <Rocket className="w-24 h-24 text-purple-600" />
                         </div>
                    </div>

                    {/* 9. Unfair Advantage (Col 7-8 / Row 1) */}
                     <div className="md:col-span-2 md:row-span-1 border-r border-b border-black/10 md:border-black p-0 flex flex-col h-full bg-white">
                         <CanvasHeader number="9" title="Unfair Advantage" subtitle="경쟁 우위" icon="🛡️" />
                         <CanvasBody value={canvasData.unfairAdvantage} onChange={(v) => handleChange("unfairAdvantage", v)} />
                    </div>

                    {/* 2. Segments (Col 9-10 / Row 1-2) */}
                    <div className="md:col-span-2 md:row-span-2 border-b border-black/10 md:border-black p-0 flex flex-col h-full bg-white">
                        <CanvasHeader number="2" title="Customer Segments" subtitle="목표 고객" icon="🎯" />
                        <CanvasBody value={canvasData.customerSegments} onChange={(v) => handleChange("customerSegments", v)} />
                    </div>

                    {/* 8. Key Metrics (Col 3-4 / Row 2) -> Below Solution */}
                    {/* Note: In grid-flow-row, this needs to be placed carefully or use specific placement. 
                        Tailwind grid auto-placement usually goes row by row.
                        
                        Current Order in DOM:
                        1. Problem (Span 2, Row 2)
                        2. Solution (Span 2, Row 1)
                        3. UVP (Span 2, Row 2)
                        4. Advantage (Span 2, Row 1)
                        5. Segments (Span 2, Row 2)
                        
                        This order is tricky for Masonry/Dense packing.
                        Instead, we can use specific grid classes like `md:col-start-XX md:row-start-XX`.
                    */}
                    
                    {/* Re-ordering for manual placement in 10-col grid */}
                    
                    {/* Row 2 fillers */}
                    
                    {/* 8. Key Metrics -> Goes under Solution (Col 3-4) */}
                    <div className="md:col-start-3 md:col-end-5 md:row-start-2 border-r border-b border-black/10 md:border-black p-0 flex flex-col h-full bg-white">
                         <CanvasHeader number="8" title="Key Metrics" subtitle="핵심 지표" icon="📊" />
                         <CanvasBody value={canvasData.keyMetrics} onChange={(v) => handleChange("keyMetrics", v)} />
                    </div>

                    {/* 5. Channels -> Goes under Advantage (Col 7-8) */}
                     <div className="md:col-start-7 md:col-end-9 md:row-start-2 border-r border-b border-black/10 md:border-black p-0 flex flex-col h-full bg-white">
                         <CanvasHeader number="5" title="Channels" subtitle="유통 채널" icon="📢" />
                         <CanvasBody value={canvasData.channels} onChange={(v) => handleChange("channels", v)} />
                    </div>

                    {/* Bottom Row */}
                    
                    {/* 7. Cost Structure (Col 1-5 / Row 3) */}
                     <div className="md:col-span-5 md:row-start-3 border-r md:border-r border-black/10 md:border-black p-0 flex flex-col min-h-[200px] bg-white">
                         <CanvasHeader number="7" title="Cost Structure" subtitle="비용 구조" icon="💸" />
                         <CanvasBody value={canvasData.costStructure} onChange={(v) => handleChange("costStructure", v)} />
                    </div>

                    {/* 6. Revenue Streams (Col 6-10 / Row 3) */}
                     <div className="md:col-span-5 md:row-start-3 border-black/10 md:border-black p-0 flex flex-col min-h-[200px] bg-white">
                         <CanvasHeader number="6" title="Revenue Streams" subtitle="수익원" icon="💰" className="text-green-700" />
                         <CanvasBody value={canvasData.revenueStreams} onChange={(v) => handleChange("revenueStreams", v)} className="text-green-900 font-medium" />
                    </div>

                </div>
            </div>
        </div>
      </div>

    </div>
  );
}

function CanvasHeader({ number, title, subtitle, icon, className }: { number: string, title: string, subtitle: string, icon: string, className?: string }) {
    return (
        <div className={`px-4 py-3 border-b border-dashed border-gray-200 flex justify-between items-center ${className}`}>
           <div>
               <h4 className="font-extrabold text-sm uppercase tracking-wide flex items-center gap-2">
                   {title}
               </h4>
               <p className="text-[10px] text-gray-400 font-medium mt-0.5">{subtitle}</p>
           </div>
           <div className="flex items-center gap-2 opacity-50">
               <span className="text-lg grayscale">{icon}</span>
               <span className="text-xs font-black border border-current rounded-full w-5 h-5 flex items-center justify-center">{number}</span>
           </div>
        </div>
    )
}

function CanvasBody({ value, onChange, className }: { value: string, onChange: (v: string) => void, className?: string }) {
    return (
        <div className="flex-1 p-0 relative group">
            <Textarea
                value={value}
                onChange={(e) => onChange(e.target.value)}
                className={`w-full h-full resize-none border-0 bg-transparent p-4 text-sm leading-relaxed focus-visible:ring-0 placeholder:text-gray-200 ${className}`}
                placeholder="..."
            />
            <div className="absolute bottom-2 right-2 text-gray-300 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none">
                <EditIcon className="w-3 h-3" />
            </div>
        </div>
    )
}

function EditIcon({ className }: { className?: string }) {
    return (
        <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
        </svg>
    )
}
